# Generated by Django 2.2.5 on 2020-09-18 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=50, verbose_name='姓（漢字）')),
                ('given_name', models.CharField(max_length=50, verbose_name='名（漢字）')),
                ('family_kana', models.CharField(max_length=50, verbose_name='姓（カタカナ）')),
                ('given_kana', models.CharField(max_length=50, verbose_name='名（カタカナ）')),
                ('department', models.CharField(max_length=225, verbose_name='所属部署')),
            ],
            options={
                'verbose_name': 'スタッフ',
                'verbose_name_plural': 'スタッフ',
            },
        ),
        migrations.CreateModel(
            name='BodyTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True, verbose_name='体温')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='検温日')),
                ('revised_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='body_temp.Staff', verbose_name='名前')),
            ],
            options={
                'verbose_name': '体温',
                'verbose_name_plural': '体温',
            },
        ),
    ]
